services:
  backend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command:
      /bin/sh -c "python3 src/wait_for_db.py && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

  database:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
