"""auto response added

Revision ID: 23289b699735
Revises: 9eb443ca205a
Create Date: 2024-08-22 01:22:18.027314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23289b699735'
down_revision: Union[str, None] = '9eb443ca205a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_auto_response', sa.Boolean(), nullable=False))
    op.add_column('posts', sa.Column('auto_response_delay', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'auto_response_delay')
    op.drop_column('posts', 'is_auto_response')
    # ### end Alembic commands ###
