"""set null added to foreign keys

Revision ID: 71f17f0e0c0d
Revises: c770aeaddc6b
Create Date: 2024-08-23 03:20:18.886497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71f17f0e0c0d'
down_revision: Union[str, None] = 'c770aeaddc6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_parent_comment_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_author_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_post_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'comments', 'comments', ['parent_comment_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'comments', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('posts_author_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_author_id_fkey', 'posts', 'users', ['author_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_post_id_fkey', 'comments', 'posts', ['post_id'], ['id'])
    op.create_foreign_key('comments_author_id_fkey', 'comments', 'users', ['author_id'], ['id'])
    op.create_foreign_key('comments_parent_comment_id_fkey', 'comments', 'comments', ['parent_comment_id'], ['id'])
    # ### end Alembic commands ###
