"""is_blocked changed to blocked_at

Revision ID: fe41c258bdba
Revises: 14c7cb631521
Create Date: 2024-08-18 14:54:24.175536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe41c258bdba'
down_revision: Union[str, None] = '14c7cb631521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('blocked_at', sa.Date(), nullable=True))
    op.drop_column('comments', 'is_blocked')
    op.add_column('posts', sa.Column('blocked_at', sa.Date(), nullable=True))
    op.drop_column('posts', 'is_blocked')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_blocked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('posts', 'blocked_at')
    op.add_column('comments', sa.Column('is_blocked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('comments', 'blocked_at')
    # ### end Alembic commands ###
